import { Container, Flex } from "@mantine/core";
import { IconLayoutGrid, IconLayoutList } from "@tabler/icons-react";
import { useContext, useState } from "react";

import { BreadCrumbs } from "@/components/breadcrumbs";
import { GlobalContext } from "@/contexts/globalContext";
import Head from "next/head";
import { MultimediaFeed } from "@/components/feed/multimedia";
import styles from "../../styles/pages/home.module.scss";
import { useRouter } from "next/router";
import { capitalizeFirstLetter } from "@/helpers/stringhelper";

export default function Multimedia() {
  const { globalConfig } = useContext(GlobalContext);
  const router = useRouter();
  const { country, region, thematicArea, mediaType } = router.query;

  // Some links generated by the CMS use semicolons between query parameters.
  // Normalize them so both `?region=africa&mediaType=video` and
  // `?region=africa;mediaType=video` work.
  const queryString = router.asPath.split("?")[1]?.split("#")[0] || "";
  const compatibleParams = new URLSearchParams(queryString.replace(/;/g, "&"));
  const getQueryValue = (name: string, value?: string | string[]) =>
    compatibleParams.get(name) ||
    (Array.isArray(value) ? value[0] : value) ||
    undefined;

  const [displayType, setDisplayType] = useState<string>("column");
  return (
    <>
      <Head>
        <title>Multimedia - The WHO Traditional Medicine Global Library</title>
      </Head>
      <Container size={"xl"} py={40}>
        <BreadCrumbs
          blackColor
          path={[
            { path: "/", name: "HOME" },
            { path: "/multimedia", name: "Multimedia" },
          ]}
        />
        <Flex justify={"space-between"} align={"center"} px={15} mt={30}>
          <h3 className={styles.TitleWithIcon} style={{ margin: "5px" }}>
            {capitalizeFirstLetter("Multimedia")}
          </h3>

          <div>
            <IconLayoutGrid
              size={30}
              onClick={() => setDisplayType("column")}
              style={{ cursor: "pointer" }}
              color={displayType == "column" ? "black" : "silver"}
            />
            <IconLayoutList
              size={30}
              onClick={() => setDisplayType("list")}
              style={{ cursor: "pointer" }}
              color={displayType != "column" ? "black" : "silver"}
            />
          </div>
        </Flex>
        <Flex px={15} mb={40}>
          <p className={styles.DescriptionThin}>
            {globalConfig?.acf.multimedia_description}
          </p>
        </Flex>

        <MultimediaFeed
          thematicArea={getQueryValue("thematicArea", thematicArea)}
          country={getQueryValue("country", country)}
          region={getQueryValue("region", region)}
          mediaType={getQueryValue("mediaType", mediaType)}
          displayType={displayType}
        />
      </Container>
    </>
  );
}
